### ISSUE TITLE
[Feature]: Merging interfaces of @tanstack/react-query and @suspensive/react into @suspensive/react-query

### ISSUE THREAD

**Issue by sonsurim** [suspensive/react#831]
### Package Scope

@suspensive/react-query

### Description

Thank you for making great open source.
the number of apis provided by suspensive/react-query is increasing.

Tanstack Query is great, but it's unfortunate that there are compatibility issues.
I think suspense/react-query seem to aim to solve this problem. 

Couldn't it be provided to only use suspense/react-query?
I think it would be very convenient from the user's perspective.

**Comment by manudeli** [comment]
[WIP]

@sonsurim @minsoo-web 

# @suspensive/react-query v2 Dependencies structure candidates

## AS-IS
```tsx
```

## TO-BE

### **@suspensive/react-query v2**+ @suspensive/react v2 
```tsx
import { Suspensive, Suspense, ErrorBoundary, QueryErrorBoundary, useSuspenseQuery } from "@suspensive/react-query"
import { useQuery, QueryClientProvider } from "@tanstack/react-query"
```

### **@suspensive/react-query v2** + @suspensive/react v2 + @tanstack/react-query v4
```tsx
import { Suspensive, Suspense, ErrorBoundary, QueryErrorBoundary, useSuspenseQuery, useQuery, QueryClientProvider } from "@suspensive/react-query"
```

### **@suspensive/react-query v2** + @tanstack/react-query v4
```tsx
import { Suspensive, Suspense, ErrorBoundary } from "@suspensive/react"
import { QueryErrorBoundary, useSuspenseQuery, useQuery, QueryClientProvider } from "@suspensive/react-query"
```

**Comment by tooooo1** [comment]
I'm proposing **a new opinion**:
### query handling directly within `@suspensive/react`?

I'm considering a unified format, similar to how specific functionalities are packaged in other libraries. For instance, akin to integrating `Zod` with `React Hook Form` or how `Vercel` handles `analytics`.

Proposed naming and structure could be:

`@suspensive/react/query`

This would allow us to import components and hooks related to querying directly from the unified package, streamlining the integration process and reducing complexity. For example:

```tsx
import { useSuspenseQuery, QueryClientProvider } from '@suspensive/react/query';
```

This approach would not only simplify the dependency management but could also enhance the coherence and usability of the library. What are your thoughts on this proposal?

**Comment by sonsurim** [comment]
Thank you so much for your suggestions!
I think this is an issue that should be discussed as far as the direction of `suspensive`, so we'll have to be careful.🧐

If it stays in its current direction, I'd like to see `suspensive/react-query` not limit the versions of `Tanstack/query`.

### AS-IS
- User: Using  Tanstack/query v4

### TO-BE
- Users: Using Tanstack/query v4 or v5

Someone might ask: "Why should I use `suspensive/react-query` if I update to Tanstack Query v5?".

For those users, I'd like to see the benefits of `suspensive/react-query` in the official documentation, as shown below:
- While Tanstack Query v5 is optimized for newer browsers than previous versions, `suspensive/react-query` are compatible with more browser configs. 
- It provides features that I had to customize and implement myself while using Tanstack Query. 
- It gives you the ability to use the new APIs in V5 while still using Tanstack Query V4.

It would also be nice to see some guidance on who they are recommended for and in what situations they are needed.

I may be wrong about the benefits of `suspensive/react-query`. But if the above is correct, I think it would be attractive to users when they see the documentation.

Finally, thank you so much for your interest in the issue!

**Comment by manudeli** [comment]
> * While Tanstack Query v5 is optimized for newer browsers than previous versions, `suspensive/react-query` are compatible with more browser configs.
> * It provides features that I had to customize and implement myself while using Tanstack Query.
> * It gives you the ability to use the new APIs in V5 while still using Tanstack Query V4.

Thanks for your new suggestion! I think this is one of good approach to solve this issue.

In my opinion, This issue's main pain point is setuping Suspensive is quite hard to use this intuitively.
And migrating @suspensive/react-query into @suspensive/react/query can be one of good way to reduce our library users' effort. but if we should use subpath(like @suspensive/react/query) to support @suspensive/react's @tanstack/react-query adpater. Library users should know below.

- how to configure tsconfig for using subpath of library
https://www.typescriptlang.org/tsconfig#moduleResolution
- Node 10 don't support using subpath
https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/NoResolution.md#common-causes

If we need to reduce library users' effort for setup Suspensive, I think subpath also can be another obstacle for configuring library.

So, I want to rule out that add @suspensive/react-query as subpath of library

**Comment by manudeli** [comment]
> Thank you so much for your suggestions! I think this is an issue that should be discussed as far as the direction of `suspensive`, so we'll have to be careful.🧐
> 
> If it stays in its current direction, I'd like to see `suspensive/react-query` not limit the versions of `Tanstack/query`.
> 
> ### AS-IS
> * User: Using  Tanstack/query v4
> 
> ### TO-BE
> * Users: Using Tanstack/query v4 or v5
> 
> Someone might ask: "Why should I use `suspensive/react-query` if I update to Tanstack Query v5?".
> 
> For those users, I'd like to see the benefits of `suspensive/react-query` in the official documentation, as shown below:
> 
> * While Tanstack Query v5 is optimized for newer browsers than previous versions, `suspensive/react-query` are compatible with more browser configs.
> * It provides features that I had to customize and implement myself while using Tanstack Query.
> * It gives you the ability to use the new APIs in V5 while still using Tanstack Query V4.
> 
> It would also be nice to see some guidance on who they are recommended for and in what situations they are needed.
> 
> I may be wrong about the benefits of `suspensive/react-query`. But if the above is correct, I think it would be attractive to users when they see the documentation.
> 
> Finally, thank you so much for your interest in the issue!

I absolutely agree! and I would like to get agreement of our maintainers and proceed in this direction
or better suggestion making library users use our library more easily 
cc. @minsoo-web @okinawaa 

#### In my opinion, This below way is the best way to survive our library in users
- @suspensive/react v2: Suppport AS-IS samely
- @suspensive/react-query v2: Support useSuspenseQuery, useSuspenseQueries, useSuspenseInfiniteQuery, SuspenseQuery, SuspenseInfiniteQuery, queryOptions with @tanstack/react-query v4 and @suspensive/react's all interfaces. It provide all interfaces similar with @tanstack/react-query v5's one without problems even in low-version browsers and support about essential ErrorBoundary and QueryErrorBoundary at once too to use suspense in @tanstack/react-query more correctly and easily.
- @suspensive/react-query v3: Support SuspenseQuery, SuspenseInfiniteQuery with @tanstack/react-query v5 and @suspensive/react's all interfaces

**Comment by minsoo-web** [comment]
Hi @sonsurim , @tooooo1  
First of all, I'd like to thank you for submitting this issue and for your interest in it.

I **strongly agree** with your comments, and here are the changes I have in mind.

### AS-IS
People who want to use `@tanstack/react-query` (v4, v5 are not supported by our package)
-> `@suspensive/react, @suspensive/react-query, with @tanstack/react-query (v4)`

People who only want to use `suspense'
-> `@suspensive/react`


### TO-BE
People who want to use tanstack query (v4 ? v5? doesn't matter)
-> `@suspensive/react-query`

People who only want to use `suspense'
-> `@suspensive/react`

The `@suspensive/react` will be a package that contains the **logic core** to `react` as a provider and will be a dependency of `@suspensive/react-query`. By installing `@suspensive/react-query` alone, users will not experience any bugging issues and can just pull out and use the APIs they need.

Thanks again for your contributions and suggestions.

**Comment by sungh0lim** [comment]
Hi, @manudeli .
I'll leave my thoughts your opinion(TO-BE).

Let's first talk about the case where `tanstack/react-query` is added as a dependency rather than a peerDependency.

## 1. Version confusion with tanstack/react-query

Whenever the version of `tanstack/react-query` goes up, the version of `suspensive/react-query` must also go up.
However, I don't expect the two versions to be identical. So users usually want to use a specific version of `tanstack/react-query`, but it is difficult to find the corresponding version.
Most of the functions are probably from `tanstack/react-query`, but it seems difficult to respond appropriately.

## 2. Dependency problem (with. `QueryCore`)

What I'm concerned about is confusion for existing users.
If you are using suspensive/react, you will use dependency like this.
```json
{
  "dependencies": {
    "suspensive/react-query": "^1",
    "tanstack/react-query": "^4",
  }
}
```

Even if the user upgrades the version like this, no error occurs during the installation process.

```json
{
  "dependencies": {
    "suspensive/react-query": "^2",
    "tanstack/react-query": "^4",
  }
}
```

Previously, when managed as peerDependency, at least `WARN` would have been shown.

I agree with the part about merge `suspensive/react` and `suspensive/react-query`. It will be able to provide convenience in use to future users.

Thanks for suggesting about an interesting issue.

**Comment by manudeli** [comment]
@sonsurim, @tooooo1, @sungh0lim

I think the root cause of the issue is that there is confusion about which version of @tanstack/react-query, which is a dependent package of @suspensive/react-query, should be installed.

After discussing with maintainer @minsoo-web, we decided to address this issue by improving the official documentation, not any re-exporting. Of course, I think that re-exporting @tanstack/react-query suggested in the issue could be a good solution. However, you must also respond to packages such as @tanstack/react-query-devtools and @tanstack/react-query-next-experimental, and if we add @tanstack/react-query v5 as a dependency of @suspensive/react-query, it is an active package, so the dependent packages Every time a version increases, there is a need to respond to it for us. Therefore, we decided to maintain the form of peerDependencies as it is now.

However, our maintainers also greatly agree with the problem raised in the issue and that it is difficult to set up @suspensive/react-query. so We prepared an alternative and made a plan to improve it.

1. As @sungh0lim commented, this can be recognized through a warning message due to peerDependencies, and this will be clearly displayed in the official document.
2. The official documentation will specify that @tanstack/react-query v4 must be installed as shown below.
```shell
pnpm add @suspensive/react-query@2 @tanstack/react-query@4
```
3. We plan to emphasize chance of this confusion by using nextra's Callout Component in our official documents.
4. We will explain browser compatibility issues caused by es private field in @tanstack/react-query v5.
5. We are planning to prepare @suspesniv/react-query@2-tanstack-v5-0.0.1, which is compatible with @tanstack/react-query v5 too, not only v4.

Thanks for raising the issue! Your interest is making Suspensive a much better library. Let's make it together. 🙇 cc. @minsoo-web @okinawaa

**Comment by manudeli** [comment]
@sonsurim, @tooooo1, @sungh0lim

I think the root cause of the issue is that there is confusion about which version of @tanstack/react-query, which is a dependent package of @suspensive/react-query, should be installed.

After discussing with maintainer @minsoo-web, we decided to address this issue by improving the official documentation, not any re-exporting. Of course, I think that re-exporting @tanstack/react-query suggested in the issue could be a good solution. However, we must also respond to packages such as @tanstack/react-query-devtools and @tanstack/react-query-next-experimental, and if we add @tanstack/react-query v5 as a dependency of @suspensive/react-query, it is an active package, so the dependent packages Every time a version increases, there is a need to respond to it for us. Therefore, we decided to maintain the form of peerDependencies as it is now.

However, our maintainers also greatly agree with the problem raised in the issue and that it is difficult to set up @suspensive/react-query. so We prepared an alternative and made a plan to improve it.

1. As @sungh0lim commented, this can be recognized through a warning message due to peerDependencies, and this will be clearly displayed in the official document.
2. The official documentation will specify that @tanstack/react-query v4 must be installed as shown below.
```shell
pnpm add @suspensive/react-query@2 @tanstack/react-query@4
```
3. We plan to emphasize chance of this confusion by using nextra's Callout Component in our official documents.
4. We will explain browser compatibility issues caused by es private field in @tanstack/react-query v5.
5. We are planning to prepare @suspesniv/react-query@2-tanstack-v5-0.0.1, which is compatible with @tanstack/react-query v5 too, not only v4.

Thanks for raising the issue! Your interest is making Suspensive a much better library. Let's make it together. 🙇 cc. @minsoo-web @okinawaa

**Comment by manudeli** [comment]
@sonsurim @tooooo1 @sungh0lim @minsoo-web @okinawaa I made Pull Request to improve motivation and guide for @suspensive/react-query and I added you guys as co-authors

And I want to introduce this Co-author generator(https://co-author-generator.vercel.app/) solve my wasting time problem to  add you guys as co-author every time

![image](https://github.com/suspensive/react/assets/61593290/a414e225-ba14-44be-875f-8d6cd3a807af)

As sure, I made it just now with @suspensive/react-query 🚀
